c_compiler:             # [osx]
  - clang_bootstrap     # [osx]
cxx_compiler:           # [osx]
c_compiler: 
- clang_bootstrap     # [osx]
- vs2022  # [win]
- gcc  # [linux]

cxx_compiler:  
- clang_bootstrap     # [osx]
- vs2022  # [win]
- gxx  # [linux]

# Stage 2: Build with clang 21 compiler
c_compiler_version:   # [osx]
  - 21.1.8            # [osx]
cxx_compiler_version: # [osx]
  - 21.1.8            # [osx]

# Keep consistent with llvmdev and clangdev
c_compiler:        # [win]
  - vs2022         # [win]
cxx_compiler:      # [win]
  - vs2022         # [win]

c_stdlib_version:  # [win]
  - 2022.14        # [win]
