c_compiler:             # [osx]
  - clang_bootstrap     # [osx]
cxx_compiler:           # [osx]
  - clang_bootstrap     # [osx]

# Note: Must use LLVM 20 compiler because clang_bootstrap 21 doesn't exist yet
c_compiler_version:   # [osx]
  - 20.1.8            # [osx]
cxx_compiler_version: # [osx]
  - 20.1.8            # [osx]

# Keep consistent with llvmdev and clangdev
c_compiler:        # [win]
  - vs2022         # [win]
cxx_compiler:      # [win]
  - vs2022         # [win]

c_stdlib_version:  # [win]
  - 2022.14        # [win]
